env_name: CartPole-v1 # RL environment name
base_path: /datastor1/jiahuikchen/vlmrm_logs # Base path to save logs and checkpoints
seed: 42 # Seed for reproducibility
description: Cartpole training using CLIP reward
tags: # Wandb tags
  - clip
reward:
  name: clip
  # pretrained_model: ViT-B-32/laion2b_s34b_b79k # CLIP model name
  pretrained_model: convnext_base/laion400m_s13b_b51k
  # pretrained_model: RN101/openai
  # Reward function used, given the pretrained_model's embeddings
    # goal_baseline_reg: eq. 3 from VLM RM paper
    # cosine: cosine similarity between target and state embeddings
    # l2: inverse of l2 distance between target and state embeddings 
  reward_func: l2 
  # Whether or not the reward is binary: 0 if <= threshold, 1 otherwise
  sparse: False 
  threshold: 0.5
  # CLIP batch size per synchronous inference step.
  # Batch size must be divisible by n_workers (GPU count)
  # so that it can be shared among workers, and must be a divisor
  # of n_envs * episode_length so that all batches can be of the
  # same size (no support for variable batch size as of now.)
  batch_size: 1600
  alpha: 0.5 # Alpha value of Baseline CLIP (CO-RELATE)
  target_prompts: # Description of the goal state
    - pole vertically upright on top of the cart
  baseline_prompts: # Description of the environment
    - pole and cart
  # Path to pre-saved model weights. When executing multiple runs,
  # mount a volume to this path to avoid downloading the model
  # weights multiple times.
  cache_dir: /datastor1/jiahuikchen/.cache
rl:
  policy_name: MlpPolicy
  n_steps: 3000000 # Total number of simulation steps to be collected.
  n_envs_per_worker: 4 # Number of environments per worker (GPU)
  episode_length: 200 # Desired episode length
  learning_starts: 75000 # Number of env steps to collect before training
  train_freq: 200 # Number of collected env steps between training iterations
  batch_size: 64 # SAC buffer sample size per gradient step
  gradient_steps: 128 # Number of samples to collect from the buffer per training step
  tau: 0.005 # SAC target network update rate
  gamma: 0.99 # SAC discount factor
  learning_rate: 2.3e-3 # SAC optimizer learning rate
logging:
  checkpoint_freq: 800 # Number of env steps between checkpoints
  video_freq: 800 # Number of env steps between videos