env_name: MountainCarContinuous-v0 # RL environment name
base_path: /data/sparajuli/training # Base path to save logs and checkpoints
seed: 42 # Seed for reproducibility
description: Cartpole training using CLIP reward
tags: # Wandb tags
  - clip
reward:
  name: clip
  # pretrained_model: ViT-B-32/laion2b_s34b_b79k # CLIP model name
  pretrained_model: google/siglip-base-patch16-224k # CLIP model name

  # CLIP batch size per synchronous inference step.
  # Batch size must be divisible by n_workers (GPU count)
  # so that it can be shared among workers, and must be a divisor
  # of n_envs * episode_length so that all batches can be of the
  # same size (no support for variable batch size as of now.)
  reward_func: goal_baseline_reg
  batch_size: 1600
  alpha: 0.5 # Alpha value of Baseline CLIP (CO-RELATE)
  target_prompts: # Description of the goal state
    - a car at the peak of the mountain, next to the yellow flag
  baseline_prompts: # Description of the environment
    - car on the mountain
  # Path to pre-saved model weights. When executing multiple runs,
  # mount a volume to this path to avoid downloading the model
  # weights multiple times.
  cache_dir: /data/sparajuli/.cache
rl:
  policy_name: MlpPolicy
  n_steps: 500000 # Total number of simulation steps to be collected.
  n_envs_per_worker: 2 # Number of environments per worker (GPU)
  episode_length: 200 # Desired episode length
  learning_starts: 100 # Number of env steps to collect before training
  train_freq: 200 # Number of collected env steps between training iterations
  batch_size: 512 # SAC buffer sample size per gradient step
  gradient_steps: 1 # Number of samples to collect from the buffer per training step
  tau: 0.01 # SAC target network update rate
  gamma: 0.9999 # SAC discount factor
  learning_rate: 10e-4 # SAC optimizer learning rate
logging:
  checkpoint_freq: 800 # Number of env steps between checkpoints
  video_freq: 800 # Number of env steps between videos
  # tensorboard_freq: 800
